/* The purpose of this program is to show working knowledge of how If, Else-If 
 * and Else conditionals are used and manipulated. Booleans, random number generators and
   nested If statements will also be demonstrated.*/
 
import java.util.Scanner;

public class IfElseIf

{
    
    public static void main(String[] args)
    
    {
        
        run(); // Run "run" method.
        
    }
    
    public static void run() // "Run" method.
    
    {
        
        int getNumber = 0; // A variable used to store values for many of the functions in the program and the value input by the user.
        String getAflAnswer = ""; // Initialises variable that will store AFL answer.
        
        Scanner input = new Scanner(System.in); // Initialise Scanner
        
        System.out.println("This program will give you a general estimate as to which Generation you are considered to belong to! A typical if statement will be used and execute the relevant part of the statement depending on the answer given by the user.");
        
        while (getNumber < 1920 || getNumber > 2010) // This While loop checks if the number input by user is between 1920 and 2010. If it is, the program continues. If it isn't, the user will be asked to put in another number.
        {
            
            System.out.println("Please enter your birth year, eg. 1971: ");
            getNumber = input.nextInt(); // Stores number input by user.  
        
        }
        
        if (getNumber <= 1945) { // If user input is less than or equal to 1945, then this part of the If statement is executed.
            
            System.out.println("You are of the World War 2/Silent Generation.");
        
        }
        
        else if (getNumber <= 1965) { // If user input is over 1945 but below or equal to 1965, then this part of the If statement is executed.
            
            System.out.println("You are of the Boomers Generation.");
            
        }
        
        else if (getNumber <= 1979) { // If user input is over 1965 but below or equal to 1979, then this part of the If statement is executed.
            
            System.out.println("You are of Generation X.");
            
        }
        
        else if (getNumber <= 1994) { // If user input is over 1979 but below or equal to 1994, then this part of the If statement is executed.
            
            System.out.println("You are of Generation Y/Millenial.");
            
        }
        
        else { // If none of the previous If statements are executed, then the program executes the one below.
            
            System.out.println("You are of Generation Z.");
            
        }
        
        
        System.out.println("The following part will run a program involving the use of a Switch statement and booleans.");
        System.out.println("You will be asked to generate a random number twice. If they match, the message at the end will return a message accordingly.");
        
        double getNumberRandom = 0; // Stores random number generated by Math.random
        int getNumber2 = 0; // Get second number input by user to compare with first number.
        boolean randomNumberMatch = false; // boolean variable for use in comparing if first number equals second number. It's not necessary but wanted to show an understanding of booleans
        
        System.out.println("Please type any number to start the random number generator.");
        getNumberRandom = input.nextInt(); // Stores number input by user.  
        getNumberRandom = Math.random(); // Generates random number between 0 and 1.
        getNumberRandom = getNumberRandom * 10; // Multiplies random number by 10.
        getNumberRandom = Math.round(getNumberRandom); // Rounds the number in getNumberRandom
        getNumber = (int) getNumberRandom; // Forces number in getNumberRandom into an int type
        
        switch (getNumber) // Switch statement used to show understanding of these statements. Different values in getNumber yield different statements that are printed.
        {
            case 0: System.out.println("Zero"); break;
            case 1: System.out.println("One"); break;
            case 2: System.out.println("Two"); break;
            case 3: System.out.println("Three"); break;
            case 4: System.out.println("Four"); break;
            case 5: System.out.println("Five"); break;
            case 6: System.out.println("Six"); break;
            case 7: System.out.println("Seven"); break;
            case 8: System.out.println("Eight"); break;
            case 9: System.out.println("Nine"); break;
            case 10: System.out.println("Ten"); break;
            default: System.out.println("You did not enter a valid integer!"); break;
        }
        
        System.out.println("Please type any number to start the random number generator for a second time.");
        getNumberRandom = input.nextInt(); // Stores number input by user.  
        getNumberRandom = Math.random(); // Generates random number between 0 and 1.
        getNumberRandom = getNumberRandom * 10; // Multiplies random number by 10.
        getNumberRandom = Math.round(getNumberRandom); // Rounds the number in getNumberRandom
        getNumber2 = (int) getNumberRandom; // Forces number in getNumberRandom into an int type
        
        switch (getNumber2) // Depending on the value stored in getNumber2, different statements will be printed on-screen.
        {
            case 0: System.out.println("Zero"); break;
            case 1: System.out.println("One"); break;
            case 2: System.out.println("Two"); break;
            case 3: System.out.println("Three"); break;
            case 4: System.out.println("Four"); break;
            case 5: System.out.println("Five"); break;
            case 6: System.out.println("Six"); break;
            case 7: System.out.println("Seven"); break;
            case 8: System.out.println("Eight"); break;
            case 9: System.out.println("Nine"); break;
            case 10: System.out.println("Ten"); break;
            default: System.out.println("You did not enter a valid integer!"); break; // If none of the other cases match with getNumber2, this is the default statement that is printed.
        }
        
        if (getNumber == getNumber2) { // Checks if getNumber value is equal to getNumber2 value.
            
            randomNumberMatch = true; // Boolean changed to "true" if getNumber and getNumber2 match
            System.out.println("Both random numbers match!");
            
        }
        else {
                
                System.out.println("Both random numbers don't match!"); // Printed on-screen is numbers don't match
                
        }
        
        System.out.println("This following part of the program will execute different parts of an if statement depending on the answer to the question which will used as a String value.");
        System.out.print("Do you watch the AFL (Australian Football League)? Please answer yes or no.");
        getAflAnswer = input.next(); // Stores user input
        String convertAflLower = getAflAnswer.toLowerCase(); // Changes text stored in getAflAnswer to lowercase.
        
        if (convertAflLower.equals("y") || convertAflLower.equals("yes")) // Restricts If statement to only checking for two specific answers and executing if the condition is true
        {
            System.out.println("Very nice!");
            
            System.out.print("Have you been watching the AFL for a long time? Please answer yes or no.");
            getAflAnswer = input.next();
            convertAflLower = getAflAnswer.toLowerCase();
            
            if (convertAflLower.equals("y") || convertAflLower.equals("yes")) { // Decided to include a nested IF statement here to expand on the first question
                
                System.out.println("You're a true fan!");
                
            }
            else {
                
                System.out.println("Welcome to the club!");
                
            }

        }
        
        else if (convertAflLower.equals("n") || convertAflLower.equals("no")) { // Restricts If statement to only checking for two specific answers and executing if the condition is true
            System.out.println("Oh, that's a shame!");
            
            System.out.print("Have you ever watched the AFL before? Please answer yes or no.");
            getAflAnswer = input.next();
            convertAflLower = getAflAnswer.toLowerCase();
            
            if (convertAflLower.equals("y") || convertAflLower.equals("yes")) {
                
                System.out.println("Hopefully you'll give it another chance someday!");
                
            }
            else {
                
                System.out.println("You should try it sometime!");
                
            }

        }
        
        else {
            
            System.out.println("You should try it sometime!");
            
        }
        
    }
}